name: Creating a Github Page

on: push

jobs:
  copy:
    name: copy file
    runs-on: ubuntu-latest
    env:
      FIRST_NAME: Carlos
      last_name: Medina
    steps:
      - name: say my full name
        env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $FIRST_NAME $last_name and also ${{github.ref}} and my age "${{ toJson(github) }}"
        shell: sh
